<?php
include __DIR__ . '/erreurs/erreurs__joueur.php ';
include __DIR__ . '/droits/joueur.php';
include __DIR__ . '/langues/fr/joueur.php';
include __DIR__ . '/erreurs/erreurs__message.php ';
include __DIR__ . '/droits/message.php';
include __DIR__ . '/langues/fr/message.php';
include __DIR__ . '/erreurs/erreurs__parametre.php ';
include __DIR__ . '/droits/parametre.php';
include __DIR__ . '/langues/fr/parametre.php';
include __DIR__ . '/erreurs/erreurs__groupe.php ';
include __DIR__ . '/droits/groupe.php';
include __DIR__ . '/langues/fr/groupe.php';
include __DIR__ . '/erreurs/erreurs__personnage.php ';
include __DIR__ . '/droits/personnage.php';
include __DIR__ . '/langues/fr/personnage.php';
include __DIR__ . '/erreurs/erreurs__campagne.php ';
include __DIR__ . '/droits/campagne.php';
include __DIR__ . '/langues/fr/campagne.php';
include __DIR__ . '/erreurs/erreurs__tag_campagne.php ';
include __DIR__ . '/droits/tag_campagne.php';
include __DIR__ . '/langues/fr/tag_campagne.php';
include __DIR__ . '/erreurs/erreurs__carte.php ';
include __DIR__ . '/droits/carte.php';
include __DIR__ . '/langues/fr/carte.php';
include __DIR__ . '/erreurs/erreurs__objet.php ';
include __DIR__ . '/droits/objet.php';
include __DIR__ . '/langues/fr/objet.php';
include __DIR__ . '/erreurs/erreurs__type.php ';
include __DIR__ . '/droits/type.php';
include __DIR__ . '/langues/fr/type.php';
include __DIR__ . '/erreurs/erreurs__ressource.php ';
include __DIR__ . '/droits/ressource.php';
include __DIR__ . '/langues/fr/ressource.php';
include __DIR__ . '/erreurs/erreurs__tag_ressource.php ';
include __DIR__ . '/droits/tag_ressource.php';
include __DIR__ . '/langues/fr/tag_ressource.php';
include __DIR__ . '/erreurs/erreurs__messagerie.php ';
include __DIR__ . '/droits/messagerie.php';
include __DIR__ . '/langues/fr/messagerie.php';
include __DIR__ . '/erreurs/erreurs__liste_contacts.php ';
include __DIR__ . '/droits/liste_contacts.php';
include __DIR__ . '/langues/fr/liste_contacts.php';
include __DIR__ . '/erreurs/erreurs__parametre_valeur.php ';
include __DIR__ . '/droits/parametre_valeur.php';
include __DIR__ . '/langues/fr/parametre_valeur.php';
include __DIR__ . '/erreurs/erreurs__a_joueur_parametre.php ';
include __DIR__ . '/droits/a_joueur_parametre.php';
include __DIR__ . '/langues/fr/a_joueur_parametre.php';
include __DIR__ . '/erreurs/erreurs__a_candidature_joueur_groupe.php ';
include __DIR__ . '/droits/a_candidature_joueur_groupe.php';
include __DIR__ . '/langues/fr/a_candidature_joueur_groupe.php';
include __DIR__ . '/erreurs/erreurs__a_membre_joueur_groupe.php ';
include __DIR__ . '/droits/a_membre_joueur_groupe.php';
include __DIR__ . '/langues/fr/a_membre_joueur_groupe.php';
include __DIR__ . '/erreurs/erreurs__a_invitation_joueur_groupe.php ';
include __DIR__ . '/droits/a_invitation_joueur_groupe.php';
include __DIR__ . '/langues/fr/a_invitation_joueur_groupe.php';
include __DIR__ . '/erreurs/erreurs__a_carte_objet.php ';
include __DIR__ . '/droits/a_carte_objet.php';
include __DIR__ . '/langues/fr/a_carte_objet.php';
include __DIR__ . '/erreurs/erreurs__a_campagne_tag_campagne.php ';
include __DIR__ . '/droits/a_campagne_tag_campagne.php';
include __DIR__ . '/langues/fr/a_campagne_tag_campagne.php';
include __DIR__ . '/erreurs/erreurs__a_ressource_tag_ressource.php ';
include __DIR__ . '/droits/a_ressource_tag_ressource.php';
include __DIR__ . '/langues/fr/a_ressource_tag_ressource.php';
include __DIR__ . '/erreurs/erreurs__a_liste_contact_joueur.php ';
include __DIR__ . '/droits/a_liste_contact_joueur.php';
include __DIR__ . '/langues/fr/a_liste_contact_joueur.php';
