<?php

joueur::initialiser_structure();
message::initialiser_structure();
parametre::initialiser_structure();
groupe::initialiser_structure();
personnage::initialiser_structure();
campagne::initialiser_structure();
tag_campagne::initialiser_structure();
carte::initialiser_structure();
objet::initialiser_structure();
type::initialiser_structure();
ressource::initialiser_structure();
tag_ressource::initialiser_structure();
messagerie::initialiser_structure();
liste_contacts::initialiser_structure();
parametre_valeur::initialiser_structure();
a_joueur_parametre::initialiser_structure();
a_candidature_joueur_groupe::initialiser_structure();
a_membre_joueur_groupe::initialiser_structure();
a_invitation_joueur_groupe::initialiser_structure();
a_carte_objet::initialiser_structure();
a_campagne_tag_campagne::initialiser_structure();
a_ressource_tag_ressource::initialiser_structure();
a_liste_contact_joueur::initialiser_structure();
