<?php

define('REFUS_MESSAGERIE__AJOUTER', 323);
define('ERR_MESSAGERIE__AJOUTER__CODE_JOUEUR_INEXISTANT', 324);
define('REFUS_MESSAGERIE__AJOUT_BLOQUEE', 325);
define('ERR_MESSAGERIE__AJOUTER__AJOUT_REFUSE', 326);
define('ERR_MESSAGERIE__AJOUTER_3__ECHEC_AJOUT', 327);
define('ERR_MESSAGERIE__MODIFIER__CODE_MESSAGERIE_INEXISTANT', 328);
define('REFUS_MESSAGERIE__MODIFIER', 329);
define('ERR_MESSAGERIE__MODIFIER__CODE_JOUEUR_INEXISTANT', 330);
define('REFUS_MESSAGERIE__MODIFICATION_BLOQUEE', 331);
define('ERR_MESSAGERIE__MODIFIER__AUCUN_CHANGEMENT', 332);
define('ERR_MESSAGERIE__MODIFIER_3__AUCUN_CHANGEMENT', 333);
define('ERR_MESSAGERIE__SUPPRIMER_2__CODE_MESSAGERIE_INEXISTANT', 334);
define('REFUS_MESSAGERIE__SUPPRIMER', 335);
define('REFUS_MESSAGERIE__SUPPRESSION_BLOQUEE', 336);
define('ERR_MESSAGERIE__SUPPRIMER__REFUSEE', 337);
define('ERR_MESSAGERIE__SUPPRIMER_2__REFUSEE', 338);
define('ERR_MESSAGERIE__SUPPRIMER_3__REFUSEE', 339);
