<?php

define('REFUS_A_CANDIDATURE_JOUEUR_GROUPE__AJOUTER', 398);
define('ERR_A_CANDIDATURE_JOUEUR_GROUPE__AJOUTER__CODE_JOUEUR_INEXISTANT', 399);
define('ERR_A_CANDIDATURE_JOUEUR_GROUPE__AJOUTER__CODE_GROUPE_INEXISTANT', 400);
define('ERR_A_CANDIDATURE_JOUEUR_GROUPE__AJOUTER__DOUBLON', 401);
define('REFUS_A_CANDIDATURE_JOUEUR_GROUPE__AJOUT_BLOQUEE', 402);
define('ERR_A_CANDIDATURE_JOUEUR_GROUPE__AJOUTER__REFUSE', 403);
define('ERR_A_CANDIDATURE_JOUEUR_GROUPE__AJOUTER_3__ECHEC_AJOUT', 404);
define('REFUS_A_CANDIDATURE_JOUEUR_GROUPE__MODIFIER', 405);
define('ERR_A_CANDIDATURE_JOUEUR_GROUPE__MODIFIER__CODE_JOUEUR_INEXISTANT', 406);
define('ERR_A_CANDIDATURE_JOUEUR_GROUPE__MODIFIER__CODE_GROUPE_INEXISTANT', 407);
define('ERR_A_CANDIDATURE_JOUEUR_GROUPE__MODIFIER__INEXISTANT', 408);
define('REFUS_A_CANDIDATURE_JOUEUR_GROUPE__MODIFICATION_BLOQUEE', 409);
define('ERR_A_CANDIDATURE_JOUEUR_GROUPE__MODIFIER__AUCUN_CHANGEMENT', 410);
define('ERR_A_CANDIDATURE_JOUEUR_GROUPE__MODIFIER_3__AUCUN_CHANGEMENT', 411);
define('ERR_A_CANDIDATURE_JOUEUR_GROUPE__MODIFIER_4__AUCUN_CHANGEMENT', 412);
define('REFUS_A_CANDIDATURE_JOUEUR_GROUPE__SUPPRIMER', 413);
define('REFUS_A_CANDIDATURE_JOUEUR_GROUPE__SUPPRESSION_BLOQUEE', 414);
define('ERR_A_CANDIDATURE_JOUEUR_GROUPE__SUPPRIMER__REFUSE', 415);
define('ERR_A_CANDIDATURE_JOUEUR_GROUPE__SUPPRIMER_2__REFUSE', 416);
