<?php

define('REFUS_JOUEUR__AJOUTER', 100);
define('REFUS_JOUEUR__AJOUT_BLOQUEE', 101);
define('ERR_JOUEUR__AJOUTER__JOUEUR_EMAIL_DOUBLON', 102);
define('ERR_JOUEUR__AJOUTER__JOUEUR_IDENTIFIANT_DOUBLON', 103);
define('ERR_JOUEUR__AJOUTER__AJOUT_REFUSE', 104);
define('ERR_JOUEUR__AJOUTER_3__ECHEC_AJOUT', 105);
define('ERR_JOUEUR__MODIFIER__CODE_JOUEUR_INEXISTANT', 106);
define('REFUS_JOUEUR__MODIFIER', 107);
define('ACCES_CODE_JOUEUR_REFUSE', 108);
define('REFUS_JOUEUR__MODIFICATION_BLOQUEE', 109);
define('ERR_JOUEUR__MODIFIER__AUCUN_CHANGEMENT', 110);
define('ERR_JOUEUR__MODIFIER_3__AUCUN_CHANGEMENT', 111);
define('ERR_JOUEUR__MODIFIER_4__AUCUN_CHANGEMENT', 112);
define('ERR_JOUEUR__SUPPRIMER_2__CODE_JOUEUR_INEXISTANT', 113);
define('REFUS_JOUEUR__SUPPRIMER', 114);
define('REFUS_JOUEUR__SUPPRESSION_BLOQUEE', 115);
define('ERR_JOUEUR__SUPPRIMER__REFUSEE', 116);
define('ERR_JOUEUR__SUPPRIMER_2__REFUSEE', 117);
define('ERR_JOUEUR__SUPPRIMER_3__REFUSEE', 118);
