<?php

define('REFUS_PARAMETRE__AJOUTER', 141);
define('REFUS_PARAMETRE__AJOUT_BLOQUEE', 142);
define('ERR_PARAMETRE__AJOUTER__AJOUT_REFUSE', 143);
define('ERR_PARAMETRE__AJOUTER_3__ECHEC_AJOUT', 144);
define('ERR_PARAMETRE__MODIFIER__CODE_PARAMETRE_INEXISTANT', 145);
define('REFUS_PARAMETRE__MODIFIER', 146);
define('ACCES_CODE_PARAMETRE_REFUSE', 147);
define('REFUS_PARAMETRE__MODIFICATION_BLOQUEE', 148);
define('ERR_PARAMETRE__MODIFIER__AUCUN_CHANGEMENT', 149);
define('ERR_PARAMETRE__MODIFIER_3__AUCUN_CHANGEMENT', 150);
define('ERR_PARAMETRE__MODIFIER_4__AUCUN_CHANGEMENT', 151);
define('ERR_PARAMETRE__SUPPRIMER_2__CODE_PARAMETRE_INEXISTANT', 152);
define('REFUS_PARAMETRE__SUPPRIMER', 153);
define('REFUS_PARAMETRE__SUPPRESSION_BLOQUEE', 154);
define('ERR_PARAMETRE__SUPPRIMER__REFUSEE', 155);
define('ERR_PARAMETRE__SUPPRIMER_2__REFUSEE', 156);
define('ERR_PARAMETRE__SUPPRIMER_3__REFUSEE', 157);
