<?php

define('REFUS_TAG_RESSOURCE__AJOUTER', 306);
define('REFUS_TAG_RESSOURCE__AJOUT_BLOQUEE', 307);
define('ERR_TAG_RESSOURCE__AJOUTER__AJOUT_REFUSE', 308);
define('ERR_TAG_RESSOURCE__AJOUTER_3__ECHEC_AJOUT', 309);
define('ERR_TAG_RESSOURCE__MODIFIER__CODE_TAG_RESSOURCE_INEXISTANT', 310);
define('REFUS_TAG_RESSOURCE__MODIFIER', 311);
define('ACCES_CODE_TAG_RESSOURCE_REFUSE', 312);
define('REFUS_TAG_RESSOURCE__MODIFICATION_BLOQUEE', 313);
define('ERR_TAG_RESSOURCE__MODIFIER__AUCUN_CHANGEMENT', 314);
define('ERR_TAG_RESSOURCE__MODIFIER_3__AUCUN_CHANGEMENT', 315);
define('ERR_TAG_RESSOURCE__MODIFIER_4__AUCUN_CHANGEMENT', 316);
define('ERR_TAG_RESSOURCE__SUPPRIMER_2__CODE_TAG_RESSOURCE_INEXISTANT', 317);
define('REFUS_TAG_RESSOURCE__SUPPRIMER', 318);
define('REFUS_TAG_RESSOURCE__SUPPRESSION_BLOQUEE', 319);
define('ERR_TAG_RESSOURCE__SUPPRIMER__REFUSEE', 320);
define('ERR_TAG_RESSOURCE__SUPPRIMER_2__REFUSEE', 321);
define('ERR_TAG_RESSOURCE__SUPPRIMER_3__REFUSEE', 322);
