<?php

define('REFUS_A_JOUEUR_PARAMETRE__AJOUTER', 379);
define('ERR_A_JOUEUR_PARAMETRE__AJOUTER__CODE_JOUEUR_INEXISTANT', 380);
define('ERR_A_JOUEUR_PARAMETRE__AJOUTER__CODE_PARAMETRE_INEXISTANT', 381);
define('ERR_A_JOUEUR_PARAMETRE__AJOUTER__DOUBLON', 382);
define('REFUS_A_JOUEUR_PARAMETRE__AJOUT_BLOQUEE', 383);
define('ERR_A_JOUEUR_PARAMETRE__AJOUTER__REFUSE', 384);
define('ERR_A_JOUEUR_PARAMETRE__AJOUTER_3__ECHEC_AJOUT', 385);
define('REFUS_A_JOUEUR_PARAMETRE__MODIFIER', 386);
define('ERR_A_JOUEUR_PARAMETRE__MODIFIER__CODE_JOUEUR_INEXISTANT', 387);
define('ERR_A_JOUEUR_PARAMETRE__MODIFIER__CODE_PARAMETRE_INEXISTANT', 388);
define('ERR_A_JOUEUR_PARAMETRE__MODIFIER__INEXISTANT', 389);
define('REFUS_A_JOUEUR_PARAMETRE__MODIFICATION_BLOQUEE', 390);
define('ERR_A_JOUEUR_PARAMETRE__MODIFIER__AUCUN_CHANGEMENT', 391);
define('ERR_A_JOUEUR_PARAMETRE__MODIFIER_3__AUCUN_CHANGEMENT', 392);
define('ERR_A_JOUEUR_PARAMETRE__MODIFIER_4__AUCUN_CHANGEMENT', 393);
define('REFUS_A_JOUEUR_PARAMETRE__SUPPRIMER', 394);
define('REFUS_A_JOUEUR_PARAMETRE__SUPPRESSION_BLOQUEE', 395);
define('ERR_A_JOUEUR_PARAMETRE__SUPPRIMER__REFUSE', 396);
define('ERR_A_JOUEUR_PARAMETRE__SUPPRIMER_2__REFUSE', 397);
