<?php

define('REFUS_OBJET__AJOUTER', 251);
define('ERR_OBJET__AJOUTER__CODE_TYPE_INEXISTANT', 252);
define('ACCES_CODE_TYPE_REFUSE', 253);
define('REFUS_OBJET__AJOUT_BLOQUEE', 254);
define('ERR_OBJET__AJOUTER__AJOUT_REFUSE', 255);
define('ERR_OBJET__AJOUTER_3__ECHEC_AJOUT', 256);
define('ERR_OBJET__MODIFIER__CODE_OBJET_INEXISTANT', 257);
define('REFUS_OBJET__MODIFIER', 258);
define('ERR_OBJET__MODIFIER__CODE_TYPE_INEXISTANT', 259);
define('ACCES_CODE_OBJET_REFUSE', 260);
define('REFUS_OBJET__MODIFICATION_BLOQUEE', 261);
define('ERR_OBJET__MODIFIER__AUCUN_CHANGEMENT', 262);
define('ERR_OBJET__MODIFIER_3__AUCUN_CHANGEMENT', 263);
define('ERR_OBJET__MODIFIER_4__AUCUN_CHANGEMENT', 264);
define('ERR_OBJET__SUPPRIMER_2__CODE_OBJET_INEXISTANT', 265);
define('REFUS_OBJET__SUPPRIMER', 266);
define('REFUS_OBJET__SUPPRESSION_BLOQUEE', 267);
define('ERR_OBJET__SUPPRIMER__REFUSEE', 268);
define('ERR_OBJET__SUPPRIMER_2__REFUSEE', 269);
define('ERR_OBJET__SUPPRIMER_3__REFUSEE', 270);
