<?php

define('REFUS_A_LISTE_CONTACT_JOUEUR__AJOUTER', 460);
define('ERR_A_LISTE_CONTACT_JOUEUR__AJOUTER__CODE_LISTE_CONTACTS_INEXISTANT', 461);
define('ERR_A_LISTE_CONTACT_JOUEUR__AJOUTER__CODE_JOUEUR_INEXISTANT', 462);
define('ERR_A_LISTE_CONTACT_JOUEUR__AJOUTER__DOUBLON', 463);
define('REFUS_A_LISTE_CONTACT_JOUEUR__AJOUT_BLOQUEE', 464);
define('ERR_A_LISTE_CONTACT_JOUEUR__AJOUTER__REFUSE', 465);
define('ERR_A_LISTE_CONTACT_JOUEUR__AJOUTER_3__ECHEC_AJOUT', 466);
define('REFUS_A_LISTE_CONTACT_JOUEUR__MODIFIER', 467);
define('ERR_A_LISTE_CONTACT_JOUEUR__MODIFIER__CODE_LISTE_CONTACTS_INEXISTANT', 468);
define('ERR_A_LISTE_CONTACT_JOUEUR__MODIFIER__CODE_JOUEUR_INEXISTANT', 469);
define('ERR_A_LISTE_CONTACT_JOUEUR__MODIFIER__INEXISTANT', 470);
define('REFUS_A_LISTE_CONTACT_JOUEUR__MODIFICATION_BLOQUEE', 471);
define('ERR_A_LISTE_CONTACT_JOUEUR__MODIFIER__AUCUN_CHANGEMENT', 472);
define('ERR_A_LISTE_CONTACT_JOUEUR__MODIFIER_3__AUCUN_CHANGEMENT', 473);
define('ERR_A_LISTE_CONTACT_JOUEUR__MODIFIER_4__AUCUN_CHANGEMENT', 474);
define('REFUS_A_LISTE_CONTACT_JOUEUR__SUPPRIMER', 475);
define('REFUS_A_LISTE_CONTACT_JOUEUR__SUPPRESSION_BLOQUEE', 476);
define('ERR_A_LISTE_CONTACT_JOUEUR__SUPPRIMER__REFUSE', 477);
define('ERR_A_LISTE_CONTACT_JOUEUR__SUPPRIMER_2__REFUSE', 478);
