<?php

define('REFUS_GROUPE__AJOUTER', 158);
define('ERR_GROUPE__AJOUTER__CODE_CAMPAGNE_INEXISTANT', 159);
define('ACCES_CODE_CAMPAGNE_REFUSE', 160);
define('REFUS_GROUPE__AJOUT_BLOQUEE', 161);
define('ERR_GROUPE__AJOUTER__AJOUT_REFUSE', 162);
define('ERR_GROUPE__AJOUTER_3__ECHEC_AJOUT', 163);
define('ERR_GROUPE__MODIFIER__CODE_GROUPE_INEXISTANT', 164);
define('REFUS_GROUPE__MODIFIER', 165);
define('ERR_GROUPE__MODIFIER__CODE_CAMPAGNE_INEXISTANT', 166);
define('ACCES_CODE_GROUPE_REFUSE', 167);
define('REFUS_GROUPE__MODIFICATION_BLOQUEE', 168);
define('ERR_GROUPE__MODIFIER__AUCUN_CHANGEMENT', 169);
define('ERR_GROUPE__MODIFIER_3__AUCUN_CHANGEMENT', 170);
define('ERR_GROUPE__MODIFIER_4__AUCUN_CHANGEMENT', 171);
define('ERR_GROUPE__SUPPRIMER_2__CODE_GROUPE_INEXISTANT', 172);
define('REFUS_GROUPE__SUPPRIMER', 173);
define('REFUS_GROUPE__SUPPRESSION_BLOQUEE', 174);
define('ERR_GROUPE__SUPPRIMER__REFUSEE', 175);
define('ERR_GROUPE__SUPPRIMER_2__REFUSEE', 176);
define('ERR_GROUPE__SUPPRIMER_3__REFUSEE', 177);
