<?php

define('REFUS_A_CAMPAGNE_TAG_CAMPAGNE__AJOUTER', 438);
define('ERR_A_CAMPAGNE_TAG_CAMPAGNE__AJOUTER__CODE_TAG_CAMPAGNE_INEXISTANT', 439);
define('ERR_A_CAMPAGNE_TAG_CAMPAGNE__AJOUTER__CODE_CAMPAGNE_INEXISTANT', 440);
define('ERR_A_CAMPAGNE_TAG_CAMPAGNE__AJOUTER__DOUBLON', 441);
define('REFUS_A_CAMPAGNE_TAG_CAMPAGNE__AJOUT_BLOQUEE', 442);
define('ERR_A_CAMPAGNE_TAG_CAMPAGNE__AJOUTER__REFUSE', 443);
define('ERR_A_CAMPAGNE_TAG_CAMPAGNE__AJOUTER_3__ECHEC_AJOUT', 444);
define('REFUS_A_CAMPAGNE_TAG_CAMPAGNE__SUPPRIMER', 445);
define('REFUS_A_CAMPAGNE_TAG_CAMPAGNE__SUPPRESSION_BLOQUEE', 446);
define('ERR_A_CAMPAGNE_TAG_CAMPAGNE__SUPPRIMER__REFUSE', 447);
define('ERR_A_CAMPAGNE_TAG_CAMPAGNE__SUPPRIMER_2__REFUSE', 448);
