<?php

define('REFUS_A_INVITATION_JOUEUR_GROUPE__AJOUTER', 436);
define('ERR_A_INVITATION_JOUEUR_GROUPE__AJOUTER__CODE_JOUEUR_INEXISTANT', 437);
define('ERR_A_INVITATION_JOUEUR_GROUPE__AJOUTER__CODE_GROUPE_INEXISTANT', 438);
define('ERR_A_INVITATION_JOUEUR_GROUPE__AJOUTER__DOUBLON', 439);
define('REFUS_A_INVITATION_JOUEUR_GROUPE__AJOUT_BLOQUEE', 440);
define('ERR_A_INVITATION_JOUEUR_GROUPE__AJOUTER__REFUSE', 441);
define('ERR_A_INVITATION_JOUEUR_GROUPE__AJOUTER_3__ECHEC_AJOUT', 442);
define('REFUS_A_INVITATION_JOUEUR_GROUPE__MODIFIER', 443);
define('ERR_A_INVITATION_JOUEUR_GROUPE__MODIFIER__CODE_JOUEUR_INEXISTANT', 444);
define('ERR_A_INVITATION_JOUEUR_GROUPE__MODIFIER__CODE_GROUPE_INEXISTANT', 445);
define('ERR_A_INVITATION_JOUEUR_GROUPE__MODIFIER__INEXISTANT', 446);
define('REFUS_A_INVITATION_JOUEUR_GROUPE__MODIFICATION_BLOQUEE', 447);
define('ERR_A_INVITATION_JOUEUR_GROUPE__MODIFIER__AUCUN_CHANGEMENT', 448);
define('ERR_A_INVITATION_JOUEUR_GROUPE__MODIFIER_3__AUCUN_CHANGEMENT', 449);
define('ERR_A_INVITATION_JOUEUR_GROUPE__MODIFIER_4__AUCUN_CHANGEMENT', 450);
define('REFUS_A_INVITATION_JOUEUR_GROUPE__SUPPRIMER', 451);
define('REFUS_A_INVITATION_JOUEUR_GROUPE__SUPPRESSION_BLOQUEE', 452);
define('ERR_A_INVITATION_JOUEUR_GROUPE__SUPPRIMER__REFUSE', 453);
define('ERR_A_INVITATION_JOUEUR_GROUPE__SUPPRIMER_2__REFUSE', 454);
