<?php

define('REFUS_LISTE_CONTACTS__AJOUTER', 341);
define('ERR_LISTE_CONTACTS__AJOUTER__CODE_JOUEUR_INEXISTANT', 342);
define('REFUS_LISTE_CONTACTS__AJOUT_BLOQUEE', 343);
define('ERR_LISTE_CONTACTS__AJOUTER__AJOUT_REFUSE', 344);
define('ERR_LISTE_CONTACTS__AJOUTER_3__ECHEC_AJOUT', 345);
define('ERR_LISTE_CONTACTS__MODIFIER__CODE_LISTE_CONTACTS_INEXISTANT', 346);
define('REFUS_LISTE_CONTACTS__MODIFIER', 347);
define('ERR_LISTE_CONTACTS__MODIFIER__CODE_JOUEUR_INEXISTANT', 348);
define('ACCES_CODE_LISTE_CONTACTS_REFUSE', 349);
define('REFUS_LISTE_CONTACTS__MODIFICATION_BLOQUEE', 350);
define('ERR_LISTE_CONTACTS__MODIFIER__AUCUN_CHANGEMENT', 351);
define('ERR_LISTE_CONTACTS__MODIFIER_3__AUCUN_CHANGEMENT', 352);
define('ERR_LISTE_CONTACTS__MODIFIER_4__AUCUN_CHANGEMENT', 353);
define('ERR_LISTE_CONTACTS__SUPPRIMER_2__CODE_LISTE_CONTACTS_INEXISTANT', 354);
define('REFUS_LISTE_CONTACTS__SUPPRIMER', 355);
define('REFUS_LISTE_CONTACTS__SUPPRESSION_BLOQUEE', 356);
define('ERR_LISTE_CONTACTS__SUPPRIMER__REFUSEE', 357);
define('ERR_LISTE_CONTACTS__SUPPRIMER_2__REFUSEE', 358);
define('ERR_LISTE_CONTACTS__SUPPRIMER_3__REFUSEE', 359);
