<?php

define('REFUS_A_MEMBRE_JOUEUR_GROUPE__AJOUTER', 390);
define('ERR_A_MEMBRE_JOUEUR_GROUPE__AJOUTER__CODE_GROUPE_INEXISTANT', 391);
define('ERR_A_MEMBRE_JOUEUR_GROUPE__AJOUTER__CODE_JOUEUR_INEXISTANT', 392);
define('ERR_A_MEMBRE_JOUEUR_GROUPE__AJOUTER__DOUBLON', 393);
define('REFUS_A_MEMBRE_JOUEUR_GROUPE__AJOUT_BLOQUEE', 394);
define('ERR_A_MEMBRE_JOUEUR_GROUPE__AJOUTER__REFUSE', 395);
define('ERR_A_MEMBRE_JOUEUR_GROUPE__AJOUTER_3__ECHEC_AJOUT', 396);
define('REFUS_A_MEMBRE_JOUEUR_GROUPE__MODIFIER', 397);
define('ERR_A_MEMBRE_JOUEUR_GROUPE__MODIFIER__CODE_GROUPE_INEXISTANT', 398);
define('ERR_A_MEMBRE_JOUEUR_GROUPE__MODIFIER__CODE_JOUEUR_INEXISTANT', 399);
define('ERR_A_MEMBRE_JOUEUR_GROUPE__MODIFIER__INEXISTANT', 400);
define('REFUS_A_MEMBRE_JOUEUR_GROUPE__MODIFICATION_BLOQUEE', 401);
define('ERR_A_MEMBRE_JOUEUR_GROUPE__MODIFIER__AUCUN_CHANGEMENT', 402);
define('ERR_A_MEMBRE_JOUEUR_GROUPE__MODIFIER_3__AUCUN_CHANGEMENT', 403);
define('ERR_A_MEMBRE_JOUEUR_GROUPE__MODIFIER_4__AUCUN_CHANGEMENT', 404);
define('REFUS_A_MEMBRE_JOUEUR_GROUPE__SUPPRIMER', 405);
define('REFUS_A_MEMBRE_JOUEUR_GROUPE__SUPPRESSION_BLOQUEE', 406);
define('ERR_A_MEMBRE_JOUEUR_GROUPE__SUPPRIMER__REFUSE', 407);
define('ERR_A_MEMBRE_JOUEUR_GROUPE__SUPPRIMER_2__REFUSE', 408);
