<?php

define('REFUS_A_RESSOURCE_TAG_RESSOURCE__AJOUTER', 449);
define('ERR_A_RESSOURCE_TAG_RESSOURCE__AJOUTER__CODE_TAG_RESSOURCE_INEXISTANT', 450);
define('ERR_A_RESSOURCE_TAG_RESSOURCE__AJOUTER__CODE_RESSOURCE_INEXISTANT', 451);
define('ERR_A_RESSOURCE_TAG_RESSOURCE__AJOUTER__DOUBLON', 452);
define('REFUS_A_RESSOURCE_TAG_RESSOURCE__AJOUT_BLOQUEE', 453);
define('ERR_A_RESSOURCE_TAG_RESSOURCE__AJOUTER__REFUSE', 454);
define('ERR_A_RESSOURCE_TAG_RESSOURCE__AJOUTER_3__ECHEC_AJOUT', 455);
define('REFUS_A_RESSOURCE_TAG_RESSOURCE__SUPPRIMER', 456);
define('REFUS_A_RESSOURCE_TAG_RESSOURCE__SUPPRESSION_BLOQUEE', 457);
define('ERR_A_RESSOURCE_TAG_RESSOURCE__SUPPRIMER__REFUSE', 458);
define('ERR_A_RESSOURCE_TAG_RESSOURCE__SUPPRIMER_2__REFUSE', 459);
