<?php

define('REFUS_MESSAGE__AJOUTER', 119);
define('ERR_MESSAGE__AJOUTER__CODE_MESSAGERIE_INEXISTANT', 120);
define('ERR_MESSAGE__AJOUTER__CODE_JOUEUR_INEXISTANT', 121);
define('ACCES_CODE_MESSAGERIE_REFUSE', 122);
define('REFUS_MESSAGE__AJOUT_BLOQUEE', 123);
define('ERR_MESSAGE__AJOUTER__AJOUT_REFUSE', 124);
define('ERR_MESSAGE__AJOUTER_3__ECHEC_AJOUT', 125);
define('ERR_MESSAGE__MODIFIER__CODE_MESSAGE_INEXISTANT', 126);
define('REFUS_MESSAGE__MODIFIER', 127);
define('ERR_MESSAGE__MODIFIER__CODE_MESSAGERIE_INEXISTANT', 128);
define('ERR_MESSAGE__MODIFIER__CODE_JOUEUR_INEXISTANT', 129);
define('ACCES_CODE_MESSAGE_REFUSE', 130);
define('REFUS_MESSAGE__MODIFICATION_BLOQUEE', 131);
define('ERR_MESSAGE__MODIFIER__AUCUN_CHANGEMENT', 132);
define('ERR_MESSAGE__MODIFIER_3__AUCUN_CHANGEMENT', 133);
define('ERR_MESSAGE__MODIFIER_4__AUCUN_CHANGEMENT', 134);
define('ERR_MESSAGE__SUPPRIMER_2__CODE_MESSAGE_INEXISTANT', 135);
define('REFUS_MESSAGE__SUPPRIMER', 136);
define('REFUS_MESSAGE__SUPPRESSION_BLOQUEE', 137);
define('ERR_MESSAGE__SUPPRIMER__REFUSEE', 138);
define('ERR_MESSAGE__SUPPRIMER_2__REFUSEE', 139);
define('ERR_MESSAGE__SUPPRIMER_3__REFUSEE', 140);
