<?php

define('REFUS_TAG_CAMPAGNE__AJOUTER', 215);
define('REFUS_TAG_CAMPAGNE__AJOUT_BLOQUEE', 216);
define('ERR_TAG_CAMPAGNE__AJOUTER__AJOUT_REFUSE', 217);
define('ERR_TAG_CAMPAGNE__AJOUTER_3__ECHEC_AJOUT', 218);
define('ERR_TAG_CAMPAGNE__MODIFIER__CODE_TAG_CAMPAGNE_INEXISTANT', 219);
define('REFUS_TAG_CAMPAGNE__MODIFIER', 220);
define('ACCES_CODE_TAG_CAMPAGNE_REFUSE', 221);
define('REFUS_TAG_CAMPAGNE__MODIFICATION_BLOQUEE', 222);
define('ERR_TAG_CAMPAGNE__MODIFIER__AUCUN_CHANGEMENT', 223);
define('ERR_TAG_CAMPAGNE__MODIFIER_3__AUCUN_CHANGEMENT', 224);
define('ERR_TAG_CAMPAGNE__MODIFIER_4__AUCUN_CHANGEMENT', 225);
define('ERR_TAG_CAMPAGNE__SUPPRIMER_2__CODE_TAG_CAMPAGNE_INEXISTANT', 226);
define('REFUS_TAG_CAMPAGNE__SUPPRIMER', 227);
define('REFUS_TAG_CAMPAGNE__SUPPRESSION_BLOQUEE', 228);
define('ERR_TAG_CAMPAGNE__SUPPRIMER__REFUSEE', 229);
define('ERR_TAG_CAMPAGNE__SUPPRIMER_2__REFUSEE', 230);
define('ERR_TAG_CAMPAGNE__SUPPRIMER_3__REFUSEE', 231);
