<?php

define('REFUS_CAMPAGNE__AJOUTER', 199);
define('REFUS_CAMPAGNE__AJOUT_BLOQUEE', 200);
define('ERR_CAMPAGNE__AJOUTER__AJOUT_REFUSE', 201);
define('ERR_CAMPAGNE__AJOUTER_3__ECHEC_AJOUT', 202);
define('ERR_CAMPAGNE__MODIFIER__CODE_CAMPAGNE_INEXISTANT', 203);
define('REFUS_CAMPAGNE__MODIFIER', 204);
define('REFUS_CAMPAGNE__MODIFICATION_BLOQUEE', 205);
define('ERR_CAMPAGNE__MODIFIER__AUCUN_CHANGEMENT', 206);
define('ERR_CAMPAGNE__MODIFIER_3__AUCUN_CHANGEMENT', 207);
define('ERR_CAMPAGNE__MODIFIER_4__AUCUN_CHANGEMENT', 208);
define('ERR_CAMPAGNE__SUPPRIMER_2__CODE_CAMPAGNE_INEXISTANT', 209);
define('REFUS_CAMPAGNE__SUPPRIMER', 210);
define('REFUS_CAMPAGNE__SUPPRESSION_BLOQUEE', 211);
define('ERR_CAMPAGNE__SUPPRIMER__REFUSEE', 212);
define('ERR_CAMPAGNE__SUPPRIMER_2__REFUSEE', 213);
define('ERR_CAMPAGNE__SUPPRIMER_3__REFUSEE', 214);
