<?php

define('REFUS_A_INVITATION_JOUEUR_GROUPE__AJOUTER', 409);
define('ERR_A_INVITATION_JOUEUR_GROUPE__AJOUTER__CODE_JOUEUR_INEXISTANT', 410);
define('ERR_A_INVITATION_JOUEUR_GROUPE__AJOUTER__CODE_GROUPE_INEXISTANT', 411);
define('ERR_A_INVITATION_JOUEUR_GROUPE__AJOUTER__DOUBLON', 412);
define('REFUS_A_INVITATION_JOUEUR_GROUPE__AJOUT_BLOQUEE', 413);
define('ERR_A_INVITATION_JOUEUR_GROUPE__AJOUTER__REFUSE', 414);
define('ERR_A_INVITATION_JOUEUR_GROUPE__AJOUTER_3__ECHEC_AJOUT', 415);
define('REFUS_A_INVITATION_JOUEUR_GROUPE__MODIFIER', 416);
define('ERR_A_INVITATION_JOUEUR_GROUPE__MODIFIER__CODE_JOUEUR_INEXISTANT', 417);
define('ERR_A_INVITATION_JOUEUR_GROUPE__MODIFIER__CODE_GROUPE_INEXISTANT', 418);
define('ERR_A_INVITATION_JOUEUR_GROUPE__MODIFIER__INEXISTANT', 419);
define('REFUS_A_INVITATION_JOUEUR_GROUPE__MODIFICATION_BLOQUEE', 420);
define('ERR_A_INVITATION_JOUEUR_GROUPE__MODIFIER__AUCUN_CHANGEMENT', 421);
define('ERR_A_INVITATION_JOUEUR_GROUPE__MODIFIER_3__AUCUN_CHANGEMENT', 422);
define('ERR_A_INVITATION_JOUEUR_GROUPE__MODIFIER_4__AUCUN_CHANGEMENT', 423);
define('REFUS_A_INVITATION_JOUEUR_GROUPE__SUPPRIMER', 424);
define('REFUS_A_INVITATION_JOUEUR_GROUPE__SUPPRESSION_BLOQUEE', 425);
define('ERR_A_INVITATION_JOUEUR_GROUPE__SUPPRIMER__REFUSE', 426);
define('ERR_A_INVITATION_JOUEUR_GROUPE__SUPPRIMER_2__REFUSE', 427);
