<?php

define('REFUS_A_CARTE_OBJET__AJOUTER', 455);
define('ERR_A_CARTE_OBJET__AJOUTER__CODE_CARTE_INEXISTANT', 456);
define('ERR_A_CARTE_OBJET__AJOUTER__CODE_OBJET_INEXISTANT', 457);
define('ERR_A_CARTE_OBJET__AJOUTER__DOUBLON', 458);
define('REFUS_A_CARTE_OBJET__AJOUT_BLOQUEE', 459);
define('ERR_A_CARTE_OBJET__AJOUTER__REFUSE', 460);
define('ERR_A_CARTE_OBJET__AJOUTER_3__ECHEC_AJOUT', 461);
define('REFUS_A_CARTE_OBJET__SUPPRIMER', 462);
define('REFUS_A_CARTE_OBJET__SUPPRESSION_BLOQUEE', 463);
define('ERR_A_CARTE_OBJET__SUPPRIMER__REFUSE', 464);
define('ERR_A_CARTE_OBJET__SUPPRIMER_2__REFUSE', 465);
