<?php

define('REFUS_A_CARTE_OBJET__AJOUTER', 428);
define('ERR_A_CARTE_OBJET__AJOUTER__CODE_CARTE_INEXISTANT', 429);
define('ERR_A_CARTE_OBJET__AJOUTER__CODE_OBJET_INEXISTANT', 430);
define('ERR_A_CARTE_OBJET__AJOUTER__DOUBLON', 431);
define('REFUS_A_CARTE_OBJET__AJOUT_BLOQUEE', 432);
define('ERR_A_CARTE_OBJET__AJOUTER__REFUSE', 433);
define('ERR_A_CARTE_OBJET__AJOUTER_3__ECHEC_AJOUT', 434);
define('REFUS_A_CARTE_OBJET__SUPPRIMER', 435);
define('REFUS_A_CARTE_OBJET__SUPPRESSION_BLOQUEE', 436);
define('ERR_A_CARTE_OBJET__SUPPRIMER__REFUSE', 437);
define('ERR_A_CARTE_OBJET__SUPPRIMER_2__REFUSE', 438);
