<?php

define('REFUS_A_CANDIDATURE_JOUEUR_GROUPE__AJOUTER', 370);
define('ERR_A_CANDIDATURE_JOUEUR_GROUPE__AJOUTER__CODE_JOUEUR_INEXISTANT', 371);
define('ERR_A_CANDIDATURE_JOUEUR_GROUPE__AJOUTER__CODE_GROUPE_INEXISTANT', 372);
define('ERR_A_CANDIDATURE_JOUEUR_GROUPE__AJOUTER__DOUBLON', 373);
define('REFUS_A_CANDIDATURE_JOUEUR_GROUPE__AJOUT_BLOQUEE', 374);
define('ERR_A_CANDIDATURE_JOUEUR_GROUPE__AJOUTER__REFUSE', 375);
define('ERR_A_CANDIDATURE_JOUEUR_GROUPE__AJOUTER_3__ECHEC_AJOUT', 376);
define('REFUS_A_CANDIDATURE_JOUEUR_GROUPE__MODIFIER', 377);
define('ERR_A_CANDIDATURE_JOUEUR_GROUPE__MODIFIER__CODE_JOUEUR_INEXISTANT', 378);
define('ERR_A_CANDIDATURE_JOUEUR_GROUPE__MODIFIER__CODE_GROUPE_INEXISTANT', 379);
define('ERR_A_CANDIDATURE_JOUEUR_GROUPE__MODIFIER__INEXISTANT', 380);
define('REFUS_A_CANDIDATURE_JOUEUR_GROUPE__MODIFICATION_BLOQUEE', 381);
define('ERR_A_CANDIDATURE_JOUEUR_GROUPE__MODIFIER__AUCUN_CHANGEMENT', 382);
define('ERR_A_CANDIDATURE_JOUEUR_GROUPE__MODIFIER_3__AUCUN_CHANGEMENT', 383);
define('ERR_A_CANDIDATURE_JOUEUR_GROUPE__MODIFIER_4__AUCUN_CHANGEMENT', 384);
define('REFUS_A_CANDIDATURE_JOUEUR_GROUPE__SUPPRIMER', 385);
define('REFUS_A_CANDIDATURE_JOUEUR_GROUPE__SUPPRESSION_BLOQUEE', 386);
define('ERR_A_CANDIDATURE_JOUEUR_GROUPE__SUPPRIMER__REFUSE', 387);
define('ERR_A_CANDIDATURE_JOUEUR_GROUPE__SUPPRIMER_2__REFUSE', 388);
