<?php

define('REFUS_A_MEMBRE_JOUEUR_GROUPE__AJOUTER', 417);
define('ERR_A_MEMBRE_JOUEUR_GROUPE__AJOUTER__CODE_GROUPE_INEXISTANT', 418);
define('ERR_A_MEMBRE_JOUEUR_GROUPE__AJOUTER__CODE_JOUEUR_INEXISTANT', 419);
define('ERR_A_MEMBRE_JOUEUR_GROUPE__AJOUTER__DOUBLON', 420);
define('REFUS_A_MEMBRE_JOUEUR_GROUPE__AJOUT_BLOQUEE', 421);
define('ERR_A_MEMBRE_JOUEUR_GROUPE__AJOUTER__REFUSE', 422);
define('ERR_A_MEMBRE_JOUEUR_GROUPE__AJOUTER_3__ECHEC_AJOUT', 423);
define('REFUS_A_MEMBRE_JOUEUR_GROUPE__MODIFIER', 424);
define('ERR_A_MEMBRE_JOUEUR_GROUPE__MODIFIER__CODE_GROUPE_INEXISTANT', 425);
define('ERR_A_MEMBRE_JOUEUR_GROUPE__MODIFIER__CODE_JOUEUR_INEXISTANT', 426);
define('ERR_A_MEMBRE_JOUEUR_GROUPE__MODIFIER__INEXISTANT', 427);
define('REFUS_A_MEMBRE_JOUEUR_GROUPE__MODIFICATION_BLOQUEE', 428);
define('ERR_A_MEMBRE_JOUEUR_GROUPE__MODIFIER__AUCUN_CHANGEMENT', 429);
define('ERR_A_MEMBRE_JOUEUR_GROUPE__MODIFIER_3__AUCUN_CHANGEMENT', 430);
define('ERR_A_MEMBRE_JOUEUR_GROUPE__MODIFIER_4__AUCUN_CHANGEMENT', 431);
define('REFUS_A_MEMBRE_JOUEUR_GROUPE__SUPPRIMER', 432);
define('REFUS_A_MEMBRE_JOUEUR_GROUPE__SUPPRESSION_BLOQUEE', 433);
define('ERR_A_MEMBRE_JOUEUR_GROUPE__SUPPRIMER__REFUSE', 434);
define('ERR_A_MEMBRE_JOUEUR_GROUPE__SUPPRIMER_2__REFUSE', 435);
