<?php

define('REFUS_A_LISTE_CONTACT_JOUEUR__AJOUTER', 461);
define('ERR_A_LISTE_CONTACT_JOUEUR__AJOUTER__CODE_LISTE_CONTACTS_INEXISTANT', 462);
define('ERR_A_LISTE_CONTACT_JOUEUR__AJOUTER__CODE_JOUEUR_INEXISTANT', 463);
define('ERR_A_LISTE_CONTACT_JOUEUR__AJOUTER__DOUBLON', 464);
define('REFUS_A_LISTE_CONTACT_JOUEUR__AJOUT_BLOQUEE', 465);
define('ERR_A_LISTE_CONTACT_JOUEUR__AJOUTER__REFUSE', 466);
define('ERR_A_LISTE_CONTACT_JOUEUR__AJOUTER_3__ECHEC_AJOUT', 467);
define('REFUS_A_LISTE_CONTACT_JOUEUR__MODIFIER', 468);
define('ERR_A_LISTE_CONTACT_JOUEUR__MODIFIER__CODE_LISTE_CONTACTS_INEXISTANT', 469);
define('ERR_A_LISTE_CONTACT_JOUEUR__MODIFIER__CODE_JOUEUR_INEXISTANT', 470);
define('ERR_A_LISTE_CONTACT_JOUEUR__MODIFIER__INEXISTANT', 471);
define('REFUS_A_LISTE_CONTACT_JOUEUR__MODIFICATION_BLOQUEE', 472);
define('ERR_A_LISTE_CONTACT_JOUEUR__MODIFIER__AUCUN_CHANGEMENT', 473);
define('ERR_A_LISTE_CONTACT_JOUEUR__MODIFIER_3__AUCUN_CHANGEMENT', 474);
define('ERR_A_LISTE_CONTACT_JOUEUR__MODIFIER_4__AUCUN_CHANGEMENT', 475);
define('REFUS_A_LISTE_CONTACT_JOUEUR__SUPPRIMER', 476);
define('REFUS_A_LISTE_CONTACT_JOUEUR__SUPPRESSION_BLOQUEE', 477);
define('ERR_A_LISTE_CONTACT_JOUEUR__SUPPRIMER__REFUSE', 478);
define('ERR_A_LISTE_CONTACT_JOUEUR__SUPPRIMER_2__REFUSE', 479);
