<?php

define('REFUS_A_CAMPAGNE_TAG_CAMPAGNE__AJOUTER', 466);
define('ERR_A_CAMPAGNE_TAG_CAMPAGNE__AJOUTER__CODE_TAG_CAMPAGNE_INEXISTANT', 467);
define('ERR_A_CAMPAGNE_TAG_CAMPAGNE__AJOUTER__CODE_CAMPAGNE_INEXISTANT', 468);
define('ERR_A_CAMPAGNE_TAG_CAMPAGNE__AJOUTER__DOUBLON', 469);
define('REFUS_A_CAMPAGNE_TAG_CAMPAGNE__AJOUT_BLOQUEE', 470);
define('ERR_A_CAMPAGNE_TAG_CAMPAGNE__AJOUTER__REFUSE', 471);
define('ERR_A_CAMPAGNE_TAG_CAMPAGNE__AJOUTER_3__ECHEC_AJOUT', 472);
define('REFUS_A_CAMPAGNE_TAG_CAMPAGNE__SUPPRIMER', 473);
define('REFUS_A_CAMPAGNE_TAG_CAMPAGNE__SUPPRESSION_BLOQUEE', 474);
define('ERR_A_CAMPAGNE_TAG_CAMPAGNE__SUPPRIMER__REFUSE', 475);
define('ERR_A_CAMPAGNE_TAG_CAMPAGNE__SUPPRIMER_2__REFUSE', 476);
