<?php

define('REFUS_TYPE__AJOUTER', 271);
define('ERR_TYPE__AJOUTER__CODE_RESSOURCE_INEXISTANT', 272);
define('ACCES_CODE_RESSOURCE_REFUSE', 273);
define('REFUS_TYPE__AJOUT_BLOQUEE', 274);
define('ERR_TYPE__AJOUTER__AJOUT_REFUSE', 275);
define('ERR_TYPE__AJOUTER_3__ECHEC_AJOUT', 276);
define('ERR_TYPE__MODIFIER__CODE_TYPE_INEXISTANT', 277);
define('REFUS_TYPE__MODIFIER', 278);
define('ERR_TYPE__MODIFIER__CODE_RESSOURCE_INEXISTANT', 279);
define('REFUS_TYPE__MODIFICATION_BLOQUEE', 280);
define('ERR_TYPE__MODIFIER__AUCUN_CHANGEMENT', 281);
define('ERR_TYPE__MODIFIER_3__AUCUN_CHANGEMENT', 282);
define('ERR_TYPE__MODIFIER_4__AUCUN_CHANGEMENT', 283);
define('ERR_TYPE__SUPPRIMER_2__CODE_TYPE_INEXISTANT', 284);
define('REFUS_TYPE__SUPPRIMER', 285);
define('REFUS_TYPE__SUPPRESSION_BLOQUEE', 286);
define('ERR_TYPE__SUPPRIMER__REFUSEE', 287);
define('ERR_TYPE__SUPPRIMER_2__REFUSEE', 288);
define('ERR_TYPE__SUPPRIMER_3__REFUSEE', 289);
