<?php

define('REFUS_A_RESSOURCE_TAG_RESSOURCE__AJOUTER', 477);
define('ERR_A_RESSOURCE_TAG_RESSOURCE__AJOUTER__CODE_TAG_RESSOURCE_INEXISTANT', 478);
define('ERR_A_RESSOURCE_TAG_RESSOURCE__AJOUTER__CODE_RESSOURCE_INEXISTANT', 479);
define('ERR_A_RESSOURCE_TAG_RESSOURCE__AJOUTER__DOUBLON', 480);
define('REFUS_A_RESSOURCE_TAG_RESSOURCE__AJOUT_BLOQUEE', 481);
define('ERR_A_RESSOURCE_TAG_RESSOURCE__AJOUTER__REFUSE', 482);
define('ERR_A_RESSOURCE_TAG_RESSOURCE__AJOUTER_3__ECHEC_AJOUT', 483);
define('REFUS_A_RESSOURCE_TAG_RESSOURCE__SUPPRIMER', 484);
define('REFUS_A_RESSOURCE_TAG_RESSOURCE__SUPPRESSION_BLOQUEE', 485);
define('ERR_A_RESSOURCE_TAG_RESSOURCE__SUPPRIMER__REFUSE', 486);
define('ERR_A_RESSOURCE_TAG_RESSOURCE__SUPPRIMER_2__REFUSE', 487);
