<?php

define('REFUS_RESSOURCE__AJOUTER', 290);
define('REFUS_RESSOURCE__AJOUT_BLOQUEE', 291);
define('ERR_RESSOURCE__AJOUTER__AJOUT_REFUSE', 292);
define('ERR_RESSOURCE__AJOUTER_3__ECHEC_AJOUT', 293);
define('ERR_RESSOURCE__MODIFIER__CODE_RESSOURCE_INEXISTANT', 294);
define('REFUS_RESSOURCE__MODIFIER', 295);
define('REFUS_RESSOURCE__MODIFICATION_BLOQUEE', 296);
define('ERR_RESSOURCE__MODIFIER__AUCUN_CHANGEMENT', 297);
define('ERR_RESSOURCE__MODIFIER_3__AUCUN_CHANGEMENT', 298);
define('ERR_RESSOURCE__MODIFIER_4__AUCUN_CHANGEMENT', 299);
define('ERR_RESSOURCE__SUPPRIMER_2__CODE_RESSOURCE_INEXISTANT', 300);
define('REFUS_RESSOURCE__SUPPRIMER', 301);
define('REFUS_RESSOURCE__SUPPRESSION_BLOQUEE', 302);
define('ERR_RESSOURCE__SUPPRIMER__REFUSEE', 303);
define('ERR_RESSOURCE__SUPPRIMER_2__REFUSEE', 304);
define('ERR_RESSOURCE__SUPPRIMER_3__REFUSEE', 305);
