<?php

define('REFUS_A_JOUEUR_PARAMETRE__AJOUTER', 359);
define('ERR_A_JOUEUR_PARAMETRE__AJOUTER__CODE_JOUEUR_INEXISTANT', 360);
define('ERR_A_JOUEUR_PARAMETRE__AJOUTER__CODE_PARAMETRE_INEXISTANT', 361);
define('ERR_A_JOUEUR_PARAMETRE__AJOUTER__DOUBLON', 362);
define('REFUS_A_JOUEUR_PARAMETRE__AJOUT_BLOQUEE', 363);
define('ERR_A_JOUEUR_PARAMETRE__AJOUTER__REFUSE', 364);
define('ERR_A_JOUEUR_PARAMETRE__AJOUTER_3__ECHEC_AJOUT', 365);
define('REFUS_A_JOUEUR_PARAMETRE__SUPPRIMER', 366);
define('REFUS_A_JOUEUR_PARAMETRE__SUPPRESSION_BLOQUEE', 367);
define('ERR_A_JOUEUR_PARAMETRE__SUPPRIMER__REFUSE', 368);
define('ERR_A_JOUEUR_PARAMETRE__SUPPRIMER_2__REFUSE', 369);
