<?php

define('REFUS_A_LISTE_CONTACT_JOUEUR__AJOUTER', 488);
define('ERR_A_LISTE_CONTACT_JOUEUR__AJOUTER__CODE_LISTE_CONTACTS_INEXISTANT', 489);
define('ERR_A_LISTE_CONTACT_JOUEUR__AJOUTER__CODE_JOUEUR_INEXISTANT', 490);
define('ERR_A_LISTE_CONTACT_JOUEUR__AJOUTER__DOUBLON', 491);
define('REFUS_A_LISTE_CONTACT_JOUEUR__AJOUT_BLOQUEE', 492);
define('ERR_A_LISTE_CONTACT_JOUEUR__AJOUTER__REFUSE', 493);
define('ERR_A_LISTE_CONTACT_JOUEUR__AJOUTER_3__ECHEC_AJOUT', 494);
define('REFUS_A_LISTE_CONTACT_JOUEUR__MODIFIER', 495);
define('ERR_A_LISTE_CONTACT_JOUEUR__MODIFIER__CODE_LISTE_CONTACTS_INEXISTANT', 496);
define('ERR_A_LISTE_CONTACT_JOUEUR__MODIFIER__CODE_JOUEUR_INEXISTANT', 497);
define('ERR_A_LISTE_CONTACT_JOUEUR__MODIFIER__INEXISTANT', 498);
define('REFUS_A_LISTE_CONTACT_JOUEUR__MODIFICATION_BLOQUEE', 499);
define('ERR_A_LISTE_CONTACT_JOUEUR__MODIFIER__AUCUN_CHANGEMENT', 500);
define('ERR_A_LISTE_CONTACT_JOUEUR__MODIFIER_3__AUCUN_CHANGEMENT', 501);
define('ERR_A_LISTE_CONTACT_JOUEUR__MODIFIER_4__AUCUN_CHANGEMENT', 502);
define('REFUS_A_LISTE_CONTACT_JOUEUR__SUPPRIMER', 503);
define('REFUS_A_LISTE_CONTACT_JOUEUR__SUPPRESSION_BLOQUEE', 504);
define('ERR_A_LISTE_CONTACT_JOUEUR__SUPPRIMER__REFUSE', 505);
define('ERR_A_LISTE_CONTACT_JOUEUR__SUPPRIMER_2__REFUSE', 506);
