<?php

define('REFUS_LISTE_CONTACTS__AJOUTER', 340);
define('ERR_LISTE_CONTACTS__AJOUTER__CODE_JOUEUR_INEXISTANT', 341);
define('REFUS_LISTE_CONTACTS__AJOUT_BLOQUEE', 342);
define('ERR_LISTE_CONTACTS__AJOUTER__AJOUT_REFUSE', 343);
define('ERR_LISTE_CONTACTS__AJOUTER_3__ECHEC_AJOUT', 344);
define('ERR_LISTE_CONTACTS__MODIFIER__CODE_LISTE_CONTACTS_INEXISTANT', 345);
define('REFUS_LISTE_CONTACTS__MODIFIER', 346);
define('ERR_LISTE_CONTACTS__MODIFIER__CODE_JOUEUR_INEXISTANT', 347);
define('ACCES_CODE_LISTE_CONTACTS_REFUSE', 348);
define('REFUS_LISTE_CONTACTS__MODIFICATION_BLOQUEE', 349);
define('ERR_LISTE_CONTACTS__MODIFIER__AUCUN_CHANGEMENT', 350);
define('ERR_LISTE_CONTACTS__MODIFIER_3__AUCUN_CHANGEMENT', 351);
define('ERR_LISTE_CONTACTS__MODIFIER_4__AUCUN_CHANGEMENT', 352);
define('ERR_LISTE_CONTACTS__SUPPRIMER_2__CODE_LISTE_CONTACTS_INEXISTANT', 353);
define('REFUS_LISTE_CONTACTS__SUPPRIMER', 354);
define('REFUS_LISTE_CONTACTS__SUPPRESSION_BLOQUEE', 355);
define('ERR_LISTE_CONTACTS__SUPPRIMER__REFUSEE', 356);
define('ERR_LISTE_CONTACTS__SUPPRIMER_2__REFUSEE', 357);
define('ERR_LISTE_CONTACTS__SUPPRIMER_3__REFUSEE', 358);
