<?php

define('REFUS_CARTE__AJOUTER', 232);
define('ERR_CARTE__AJOUTER__CODE_GROUPE_INEXISTANT', 233);
define('REFUS_CARTE__AJOUT_BLOQUEE', 234);
define('ERR_CARTE__AJOUTER__AJOUT_REFUSE', 235);
define('ERR_CARTE__AJOUTER_3__ECHEC_AJOUT', 236);
define('ERR_CARTE__MODIFIER__CODE_CARTE_INEXISTANT', 237);
define('REFUS_CARTE__MODIFIER', 238);
define('ERR_CARTE__MODIFIER__CODE_GROUPE_INEXISTANT', 239);
define('ACCES_CODE_CARTE_REFUSE', 240);
define('REFUS_CARTE__MODIFICATION_BLOQUEE', 241);
define('ERR_CARTE__MODIFIER__AUCUN_CHANGEMENT', 242);
define('ERR_CARTE__MODIFIER_3__AUCUN_CHANGEMENT', 243);
define('ERR_CARTE__MODIFIER_4__AUCUN_CHANGEMENT', 244);
define('ERR_CARTE__SUPPRIMER_2__CODE_CARTE_INEXISTANT', 245);
define('REFUS_CARTE__SUPPRIMER', 246);
define('REFUS_CARTE__SUPPRESSION_BLOQUEE', 247);
define('ERR_CARTE__SUPPRIMER__REFUSEE', 248);
define('ERR_CARTE__SUPPRIMER_2__REFUSEE', 249);
define('ERR_CARTE__SUPPRIMER_3__REFUSEE', 250);
