<?php

define('REFUS_PARAMETRE_VALEUR__AJOUTER', 360);
define('ERR_PARAMETRE_VALEUR__AJOUTER__CODE_PARAMETRE_INEXISTANT', 361);
define('REFUS_PARAMETRE_VALEUR__AJOUT_BLOQUEE', 362);
define('ERR_PARAMETRE_VALEUR__AJOUTER__AJOUT_REFUSE', 363);
define('ERR_PARAMETRE_VALEUR__AJOUTER_3__ECHEC_AJOUT', 364);
define('ERR_PARAMETRE_VALEUR__MODIFIER__CODE_PARAMETRE_VALEUR_INEXISTANT', 365);
define('REFUS_PARAMETRE_VALEUR__MODIFIER', 366);
define('ERR_PARAMETRE_VALEUR__MODIFIER__CODE_PARAMETRE_INEXISTANT', 367);
define('ACCES_CODE_PARAMETRE_VALEUR_REFUSE', 368);
define('REFUS_PARAMETRE_VALEUR__MODIFICATION_BLOQUEE', 369);
define('ERR_PARAMETRE_VALEUR__MODIFIER__AUCUN_CHANGEMENT', 370);
define('ERR_PARAMETRE_VALEUR__MODIFIER_3__AUCUN_CHANGEMENT', 371);
define('ERR_PARAMETRE_VALEUR__MODIFIER_4__AUCUN_CHANGEMENT', 372);
define('ERR_PARAMETRE_VALEUR__SUPPRIMER_2__CODE_PARAMETRE_VALEUR_INEXISTANT', 373);
define('REFUS_PARAMETRE_VALEUR__SUPPRIMER', 374);
define('REFUS_PARAMETRE_VALEUR__SUPPRESSION_BLOQUEE', 375);
define('ERR_PARAMETRE_VALEUR__SUPPRIMER__REFUSEE', 376);
define('ERR_PARAMETRE_VALEUR__SUPPRIMER_2__REFUSEE', 377);
define('ERR_PARAMETRE_VALEUR__SUPPRIMER_3__REFUSEE', 378);
