<?php

define('REFUS_PERSONNAGE__AJOUTER', 178);
define('ERR_PERSONNAGE__AJOUTER__CODE_JOUEUR_INEXISTANT', 179);
define('ERR_PERSONNAGE__AJOUTER__CODE_GROUPE_INEXISTANT', 180);
define('REFUS_PERSONNAGE__AJOUT_BLOQUEE', 181);
define('ERR_PERSONNAGE__AJOUTER__AJOUT_REFUSE', 182);
define('ERR_PERSONNAGE__AJOUTER_3__ECHEC_AJOUT', 183);
define('ERR_PERSONNAGE__MODIFIER__CODE_PERSONNAGE_INEXISTANT', 184);
define('REFUS_PERSONNAGE__MODIFIER', 185);
define('ERR_PERSONNAGE__MODIFIER__CODE_JOUEUR_INEXISTANT', 186);
define('ERR_PERSONNAGE__MODIFIER__CODE_GROUPE_INEXISTANT', 187);
define('ACCES_CODE_PERSONNAGE_REFUSE', 188);
define('REFUS_PERSONNAGE__MODIFICATION_BLOQUEE', 189);
define('ERR_PERSONNAGE__MODIFIER__AUCUN_CHANGEMENT', 190);
define('ERR_PERSONNAGE__MODIFIER_3__AUCUN_CHANGEMENT', 191);
define('ERR_PERSONNAGE__MODIFIER_4__AUCUN_CHANGEMENT', 192);
define('ERR_PERSONNAGE__SUPPRIMER_2__CODE_PERSONNAGE_INEXISTANT', 193);
define('REFUS_PERSONNAGE__SUPPRIMER', 194);
define('REFUS_PERSONNAGE__SUPPRESSION_BLOQUEE', 195);
define('ERR_PERSONNAGE__SUPPRIMER__REFUSEE', 196);
define('ERR_PERSONNAGE__SUPPRIMER_2__REFUSEE', 197);
define('ERR_PERSONNAGE__SUPPRIMER_3__REFUSEE', 198);
