<?php

define('API_REST_ACCESS_GET_A_CAMPAGNE_TAG_CAMPAGNE', 'none');
define('API_REST_ACCESS_POST_A_CAMPAGNE_TAG_CAMPAGNE', 'none');
define('API_REST_ACCESS_PUT_A_CAMPAGNE_TAG_CAMPAGNE', 'none');
define('API_REST_ACCESS_DELETE_A_CAMPAGNE_TAG_CAMPAGNE', 'none');
define('API_REST_ACCESS_OPTIONS_A_CAMPAGNE_TAG_CAMPAGNE', 'all');
