<?php

define('API_REST_ACCESS_GET_A_INVITATION_JOUEUR_GROUPE', 'none');
define('API_REST_ACCESS_POST_A_INVITATION_JOUEUR_GROUPE', 'none');
define('API_REST_ACCESS_PUT_A_INVITATION_JOUEUR_GROUPE', 'none');
define('API_REST_ACCESS_DELETE_A_INVITATION_JOUEUR_GROUPE', 'none');
define('API_REST_ACCESS_OPTIONS_A_INVITATION_JOUEUR_GROUPE', 'all');
