<?php

define('API_REST_ACCESS_GET_A_LISTE_CONTACT_JOUEUR', 'none');
define('API_REST_ACCESS_POST_A_LISTE_CONTACT_JOUEUR', 'none');
define('API_REST_ACCESS_PUT_A_LISTE_CONTACT_JOUEUR', 'none');
define('API_REST_ACCESS_DELETE_A_LISTE_CONTACT_JOUEUR', 'none');
define('API_REST_ACCESS_OPTIONS_A_LISTE_CONTACT_JOUEUR', 'all');
