<?php

define('API_REST_ACCESS_GET_A_MEMBRE_JOUEUR_GROUPE', 'none');
define('API_REST_ACCESS_POST_A_MEMBRE_JOUEUR_GROUPE', 'none');
define('API_REST_ACCESS_PUT_A_MEMBRE_JOUEUR_GROUPE', 'none');
define('API_REST_ACCESS_DELETE_A_MEMBRE_JOUEUR_GROUPE', 'none');
define('API_REST_ACCESS_OPTIONS_A_MEMBRE_JOUEUR_GROUPE', 'all');
