<?php

define('API_REST_ACCESS_GET_A_RESSOURCE_TAG_RESSOURCE', 'none');
define('API_REST_ACCESS_POST_A_RESSOURCE_TAG_RESSOURCE', 'none');
define('API_REST_ACCESS_PUT_A_RESSOURCE_TAG_RESSOURCE', 'none');
define('API_REST_ACCESS_DELETE_A_RESSOURCE_TAG_RESSOURCE', 'none');
define('API_REST_ACCESS_OPTIONS_A_RESSOURCE_TAG_RESSOURCE', 'all');
