<?php

define('API_REST_ACCESS_GET_LISTE_CONTACTS', 'none');
define('API_REST_ACCESS_POST_LISTE_CONTACTS', 'none');
define('API_REST_ACCESS_PUT_LISTE_CONTACTS', 'none');
define('API_REST_ACCESS_DELETE_LISTE_CONTACTS', 'none');
define('API_REST_ACCESS_OPTIONS_LISTE_CONTACTS', 'all');
