<?php

define('API_REST_ACCESS_GET_PARAMETRE_VALEUR', 'none');
define('API_REST_ACCESS_POST_PARAMETRE_VALEUR', 'none');
define('API_REST_ACCESS_PUT_PARAMETRE_VALEUR', 'none');
define('API_REST_ACCESS_DELETE_PARAMETRE_VALEUR', 'none');
define('API_REST_ACCESS_OPTIONS_PARAMETRE_VALEUR', 'all');
