<?php

define('API_REST_ACCESS_GET_TAG_RESSOURCE', 'none');
define('API_REST_ACCESS_POST_TAG_RESSOURCE', 'none');
define('API_REST_ACCESS_PUT_TAG_RESSOURCE', 'none');
define('API_REST_ACCESS_DELETE_TAG_RESSOURCE', 'none');
define('API_REST_ACCESS_OPTIONS_TAG_RESSOURCE', 'all');
